name: "Setup Python and Poetry"
description: "Setups Python, Poetry and sets env.project_version"

inputs:
  poetry-version:
    description: "Version of Poetry to install"
    required: true
    default: 1.1.13
  python-version:
    description: "The Python version to use"
    required: true

runs:
  using: "composite"
  steps:
        - uses: actions/checkout@v2
        - name: Install Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ inputs.python-version }}
        - name: Install Poetry
          uses: abatilo/actions-poetry@v2.0.0
          with:
            poetry-version: ${{ inputs.poetry-version }}
        - name: Set project_version env
          run: echo "project_version=$(poetry version -s)" >> $GITHUB_ENV
          shell: bash
        - name: Test project_version env
          run: echo $project_version
          shell: bash
          
          